name: FakePlayer
version: 1.0.0
main: com.fakeplayer.FakePlayerPlugin
description: Plugin fake player cho Minecraft Paper 1.18.2
authors:
  - YourName
api-version: 1.18

commands:
  fakeplayer:
    description: Quản lý fake player
    usage: /fakeplayer <add|remove|list|reload>
    aliases: [fp]

